services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ "setFramework", [ "@contao.framework" ] ]

  topics.picker.topics_picker:
    class: Alnv\TopicsPickerProviderBundle\Picker\TopicsPickerProvider
    tags:
      - { name: contao.picker_provider, priority: 128 }